# Import .env file
spring.config.import = optional:file:.env[.properties]

# app server
app.domain=https://localhost:8080
app.domain-only = localhost

# front server
front-server.prod-domain=https://2025-capstone-project.vercel.app/
front-server.local-domain=http://localhost:3000

server.port=8080

# swagger
springdoc.swagger-ui.groups-order=DESC
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method
springdoc.pathsToMatch=/, /api/**
springdoc.api-docs.path=/api-docs
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json
springdoc.writer-with-default-pretty-printer=true

# DB
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000

# redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.username=default
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.ssl.enabled=false

# jwt
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
jwt.refresh-expiration=604800000

# smtp
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_NAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#S3
cloud.aws.s3.bucket=capstone-project-persona
cloud.aws.s3.path.profile=userData/profile
cloud.aws.s3.path.image=userData/images
cloud.aws.s3.path.voice=userData/voices
cloud.aws.s3.path.reference=reference

cloud.aws.region.static=ap-northeast-2
cloud.aws.stack.auto=false

cloud.aws.credentials.accessKey=${AWS_ACCESS_KEY}
cloud.aws.credentials.secretKey=${AWS_SECRET_KEY}