spring.application.name=persona
spring.profiles.active=prod
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.SQL=ERROR

# server
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true